name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - "main"
concurrency:
  group: ${{ github.head_ref }}-test
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 5
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: actions/setup-node@v4.0.4
        with:
          node-version-file: "package.json"
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
